import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { AiFillProject } from 'react-icons/ai'
import React, { useRef } from "react";
import ImageDiamond from '@/public/images/LogoPrincipal.png'


export default function Home() {

  return (
    <>
      <Head>
        <title>DiamondBigger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imagem}>
          <Image
            src={ImageDiamond}
            alt="foto"
            className={styles.foto}
            width={150}
            height={250}
            priority
          />
        </div>

        <div className={styles.center}>
          <div className={styles.description2}>
            <div>
              <h1 className={styles.textHome}>  Olá, seja bem vindo(a)</h1>
            </div>
            <div>
              <h3>
                Conheça mais sobre a Diamond!
              </h3>
            </div>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href={'./pageWork'}
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Projetos <span>-&gt;</span><AiFillProject style={{ marginLeft: 10 }} />
            </h2>
          </a>
          <a
            href="./about"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Sobre nós <span>-&gt;</span>
            </h2>
          </a>
          <a
            href="https://www.linkedin.com/company/diamondbigger/"
            className={styles.card}
            target="_parent"
            rel="noopener noreferrer"
          >
            <h2>
              Linkedin <span>-&gt;</span><FaLinkedin style={{ marginLeft: 10 }} />
            </h2>
            <p>
            </p>
          </a>

        </div>
      </main>
    </>
  )
}
